SELECT * FROM SALES;
-- AS --
SELECT AMOUNT AS MÝKTAR FROM SALES;

-- Aggregate Functions --
-- COUNT
SELECT COUNT(*) FROM SALES
WHERE CITY = 'ANTALYA';

-- SUM
SELECT SUM(TOTALPRICE) FROM SALES
WHERE CITY = 'ANTALYA';

-- AVG
SELECT AVG(TOTALPRICE) FROM SALES
WHERE CITY = 'ANTALYA';

-- MAX & MIN
SELECT MAX(TOTALPRICE) AS MAX_TOTAL_PRICE, MIN(TOTALPRICE) AS MIN_TOTAL_PRICE FROM SALES
WHERE CITY = 'ANTALYA';

SELECT COUNT(*) AS ROW_NUMBER,
SUM(TOTALPRICE) AS TOTAL_PRICE,
AVG(TOTALPRICE) AS MEAN_TOTAL_PRICE,
MAX(TOTALPRICE) AS MAX_TOTAL_PRICE,
MIN(TOTALPRICE) AS MIN_TOTAL_PRICE
FROM SALES
WHERE CITY = 'ANTALYA';

-- GROUP BY --
SELECT CITY, COUNT(*) AS ROW_NUMBER,
SUM(TOTALPRICE) AS TOTAL_PRICE,
AVG(TOTALPRICE) AS MEAN_TOTAL_PRICE,
MAX(TOTALPRICE) AS MAX_TOTAL_PRICE,
MIN(TOTALPRICE) AS MIN_TOTAL_PRICE
FROM SALES
WHERE CITY IN ('ÝSTANBUL', 'ANTALYA')
GROUP BY CITY
ORDER BY TOTAL_PRICE DESC;

SELECT CITY, COUNT(*) AS ROW_NUMBER,
SUM(TOTALPRICE) AS TOTAL_PRICE,
AVG(TOTALPRICE) AS MEAN_TOTAL_PRICE,
MAX(TOTALPRICE) AS MAX_TOTAL_PRICE,
MIN(TOTALPRICE) AS MIN_TOTAL_PRICE
FROM SALES
GROUP BY CITY
ORDER BY CITY asc;


SELECT CITY, DISTRICT, COUNT(*) AS ROW_NUMBER,
SUM(TOTALPRICE) AS TOTAL_PRICE,
AVG(TOTALPRICE) AS MEAN_TOTAL_PRICE,
MAX(TOTALPRICE) AS MAX_TOTAL_PRICE,
MIN(TOTALPRICE) AS MIN_TOTAL_PRICE
FROM SALES
GROUP BY CITY, DISTRICT
ORDER BY CITY, DISTRICT asc;


SELECT CATEGORY1, CATEGORY2, 
COUNT(*) AS ROW_NUMBER,
SUM(TOTALPRICE) AS TOTAL_PRICE,
AVG(TOTALPRICE) AS MEAN_TOTAL_PRICE,
MAX(TOTALPRICE) AS MAX_TOTAL_PRICE,
MIN(TOTALPRICE) AS MIN_TOTAL_PRICE
FROM SALES
GROUP BY CATEGORY1, CATEGORY2
ORDER BY CATEGORY1, CATEGORY2;

-- Example 1:
-- Ýstanbul maðazasýnýn gün bazlý satýþ rakamýný getirme.
SELECT CONVERT(DATE, DATE_) AS DATE, SUM(TOTALPRICE) AS TOTAL_PRICE 
FROM SALES
WHERE CITY = 'ÝSTANBUL'
GROUP BY  CONVERT(DATE, DATE_)
ORDER BY DATE ASC ;


-- Example 2:
-- Bir günün maðaza bazlý satýþlarýný getirme
-- En ço ksatýþ yapan ilk 5'i getir.

SELECT TOP 5
CITY, SUM(TOTALPRICE) AS TOTAL_PRICE 
FROM SALES
WHERE DATE_ BETWEEN '2019-04-23' AND '2019-04-23 23:59:59'
GROUP BY CITY
ORDER BY TOTAL_PRICE DESC

-- Example 3:
-- Belli bir cironun üstünde satýþ yapan maðazalarý getirme.
-- HAVING --
SELECT CITY, SUM(TOTALPRICE) AS TOTAL_PRICE FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE) >= 100000
ORDER BY CITY;

-- Example 4:
-- Maðazalarýn aylara göre satýþlarýný getirme.
SET LANGUAGE TURKÝSH
SELECT CITY, DATEPART(MONTH, DATE_) AS MONTHNR,
DATENAME(MONTH, DATE_) AS MONTH_NAME,
SUM(TOTALPRICE) AS TOTAL_PRICE 
FROM SALES
GROUP BY CITY, DATEPART(MONTH, DATE_), DATENAME(MONTH, DATE_)
ORDER BY 1, 2 ASC;


SELECT COUNT(DISTINCT(ITEMNAME)) FROM SALES;
-- Example 5:
-- Her bir ürün için:
-- 1- Kaç adet satýldý VE KAÇ FATURADA YER ALDI
SELECT ITEMNAME, SUM(AMOUNT) AS TOTAL_AMOUNT FROM SALES
GROUP BY ITEMNAME
ORDER BY TOTAL_AMOUNT DESC;

SELECT ITEMNAME, COUNT(*) AS SALES_AMOUNT FROM SALES
GROUP BY ITEMNAME
ORDER BY SALES_AMOUNT DESC;

-- 2- TL olarak ne kadar satýldý
SELECT ITEMNAME, SUM(TOTALPRICE) AS TOTAL_PRICE FROM SALES
GROUP BY ITEMNAME
ORDER BY TOTAL_PRICE DESC;

-- 3- Ýlk ne zaman, son ne zaman satýldý
SELECT ITEMNAME, CONVERT(DATE, MIN(DATE_)) AS FIRST_SALES_DATE, 
CONVERT(DATE, MAX(DATE_)) AS LAST_SALES_DATE FROM SALES
GROUP BY ITEMNAME
ORDER BY ITEMNAME;

-- 4- En düþük hangi fiyattan satýldý
SELECT ITEMNAME, MIN(PRICE) AS UNIT_PRICE FROM SALES
GROUP BY ITEMNAME
ORDER BY UNIT_PRICE ASC;

-- 5- En yüksek hangi fiyattan satýldý
SELECT ITEMNAME, MAX(PRICE) AS UNIT_PRICE FROM SALES
GROUP BY ITEMNAME
ORDER BY UNIT_PRICE ASC;

-- 6 Ortalama hangi fiyattan satýldý
SELECT ITEMNAME, AVG(PRICE) AS AVERAGE_PRICE FROM SALES
GROUP BY ITEMNAME
ORDER BY AVERAGE_PRICE DESC;

-- 7- YUKARIDAKÝLERÝN HEPSÝNÝ TEK BÝR SORGUDA YAZ
SELECT ITEMCODE, ITEMNAME, BRAND, CATEGORY1, CATEGORY2,
SUM(AMOUNT) AS TOTAL_AMOUNT,
SUM(TOTALPRICE) AS TOTAL_PRICE,
CONVERT(DATE, MIN(DATE_)) AS FIRST_SALES_DATE,
CONVERT(DATE, MAX(DATE_)) AS LAST_SALES_DATE,
MIN(PRICE) AS MIN_UNIT_PRICE,
MAX(PRICE) AS MAX_UNIT_PRICE,
AVG(PRICE) AS AVG_UNIT_PRICE 
FROM SALES
GROUP BY ITEMCODE, ITEMNAME, BRAND, CATEGORY1, CATEGORY2
ORDER BY ITEMCODE ASC;

-- Example 6:
-- Maðazalarýn müþteri satýlarýný getirme
SELECT BRANCH, CITY, DISTRICT, COUNT(DISTINCT(CUSTOMERCODE)) AS CUSTOMER_NUMBER FROM SALES
GROUP BY BRANCH, CITY, DISTRICT
ORDER BY BRANCH ASC;