-- Ýliþkisel Veritabaný (RDMS)
SELECT* FROM USERS
WHERE ID=1;

SELECT * FROM ADDRESS
WHERE USERID = 1;

-- GELENEKSEL YÖNTEM
-- USER - ADDRESS
SELECT U.USERNAME_, U.NAMESURNAME, U.GENDER, A.POSTALCODE, A.ADDRESSTEXT 
FROM USERS AS U, ADDRESS AS A
WHERE U.ID = A.USERID -- AND U.ID = 3;

-- USER - ADDRESS - COUNTRY
SELECT U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT, C.COUNTRY
FROM USERS AS U, ADDRESS AS A, COUNTRIES AS C
WHERE U.ID = A.USERID AND A.COUNTRYID = C.ID;

-- USER - ADDRESS - COUNTRY - CITY
SELECT U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT, C.COUNTRY, CI.CITY
FROM USERS AS U, ADDRESS AS A, COUNTRIES AS C, CITIES AS CI
WHERE U.ID = A.USERID AND 
A.COUNTRYID = C.ID AND 
A.CITYID = CI.ID;

-- USER - ADDRESS - COUNTRY - CITY - TOWN
SELECT U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT, C.COUNTRY, CI.CITY, T.TOWN
FROM USERS AS U, ADDRESS AS A, 
COUNTRIES AS C, CITIES AS CI, TOWNS AS T
WHERE U.ID = A.USERID AND 
A.COUNTRYID = C.ID AND 
A.CITYID = CI.ID AND
A.TOWNID = T.ID;

-- USER - ADDRESS - COUNTRY - CITY - TOWN - DISTRICT
SELECT
U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT, 
C.COUNTRY, 
CI.CITY, 
T.TOWN, 
DT.DISTRICT
FROM USERS AS U, ADDRESS AS A, 
COUNTRIES AS C, CITIES AS CI, 
TOWNS AS T, DISTRICTS AS DT
WHERE 
U.ID = A.USERID AND 
A.COUNTRYID = C.ID AND 
A.CITYID = CI.ID AND
A.TOWNID = T.ID AND
A.DISTRICTID = DT.ID;

-- JOINS
-- USER - ADDRESS
SELECT U.USERNAME_, U.NAMESURNAME, U.GENDER, A.POSTALCODE, A.ADDRESSTEXT
FROM USERS AS U
JOIN ADDRESS AS A
ON U.ID = A.USERID
WHERE U.ID = 1;

-- USER - ADDRESS - COUNTRY
SELECT 
U.USERNAME_, U.NAMESURNAME, U.GENDER, 
A.POSTALCODE, A.ADDRESSTEXT,
C.COUNTRY
FROM USERS AS U
JOIN ADDRESS AS A ON U.ID = A.USERID
JOIN COUNTRIES AS C ON A.COUNTRYID = C.ID
WHERE U.ID = 1;

-- USER - ADDRESS - COUNTRY - CITY
SELECT
U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT,
C.COUNTRY, CI.CITY
FROM USERS AS U
JOIN ADDRESS AS A ON U.ID = A.USERID
JOIN COUNTRIES AS C ON A.COUNTRYID = C.ID
JOIN CITIES AS CI ON A.CITYID = CI.ID
WHERE U.ID = 1;

-- USER - ADDRESS - COUNTRY - CITY - TOWN - DISTRICT
SELECT
U.USERNAME_, U.NAMESURNAME, U.GENDER,
A.POSTALCODE, A.ADDRESSTEXT,
C.COUNTRY, CI.CITY,
T.TOWN, D.DISTRICT
FROM USERS AS U
JOIN ADDRESS AS A ON U.ID = A.USERID
JOIN COUNTRIES AS C ON A.COUNTRYID = C.ID
JOIN CITIES AS CI ON A.CITYID = CI.ID
JOIN TOWNS AS T ON A.TOWNID = T.ID
JOIN DISTRICTS AS D ON A.DISTRICTID = D.ID
order by u.USERNAME_;


SELECT * FROM ORDERS WHERE ID=1
SELECT * FROM ORDERDETAILS WHERE ORDERID=1
SELECT * FROM ITEMS WHERE ID=660
SELECT * FROM USERS WHERE ID=7678
SELECT * FROM ADDRESS WHERE ID=18770;

SELECT 
O.ID, O.DATE_, O.TOTALPRICE, OD.AMOUNT, 
I.ITEMCODE, I.ITEMCODE, I.BRAND, I.CATEGORY1,
U.USERNAME_, U.NAMESURNAME, A.ADDRESSTEXT, A.POSTALCODE,
OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL
FROM ORDERS AS O
JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID
JOIN ITEMS AS I ON I.ID = OD.ITEMID
JOIN USERS AS U ON U.ID = O.USERID
JOIN ADDRESS AS A ON A.ID = O.ADDRESSID
ORDER BY ID ASC;

-- JOIN TYPES --
-- 1. INNER JOIN (KESÝÞÝM)
-- 2. LEFT OUTER JOIN (SOL KÜMEDEKÝ BÜTÜN KAYITLARI GETÝRÝR (ÝÇERÝSÝNDE ORTAK KÜMEYÝ DE BARINDIRIR))
-- 3. RIGHT OUTER JOIN (SAÐ KÜMEDEKÝ BÜTÜN KAYITLARI GETÝRÝR (ÝÇERÝSÝNDE ORTAK KÜMEYÝ DE BARINDIRIR))
-- FULL JOIN (TÜM ÝKÝ KÜMEYÝ ALIR)

-- Example 1:
-- Þehirlere göre verilen sipariþleri toplam olarak listeleme
SELECT TOP 5 * FROM CITIES
SELECT TOP 5 * FROM ORDERS
SELECT TOP 5 * FROM ADDRESS

SELECT CITY, SUM(TOTALPRICE) AS TOTAL_PRICE
FROM ADDRESS
INNER JOIN ORDERS 
ON ADDRESS.ID = ORDERS.ADDRESSID
INNER JOIN CITIES
ON ADDRESS.CITYID = CITIES.ID
GROUP BY CITY --(CITIES.CITY 2.WAY)
ORDER BY TOTAL_PRICE DESC

-- Example 2:
-- Ürün kategorilerine göre sipariþ daðýlýmý
SELECT TOP 5 * FROM ITEMS
SELECT TOP 5 * FROM PAYMENTS
SELECT TOP 5 * FROM ORDERS
SELECT TOP 5 * FROM ORDERDETAILS

SELECT CATEGORY1, CATEGORY2, SUM(LINETOTAL) AS TOTAL_PRICE
FROM ITEMS
INNER JOIN ORDERDETAILS
ON ITEMS.ID = ORDERDETAILS.ITEMID
INNER JOIN ORDERS
ON ORDERDETAILS.ORDERID = ORDERS.ID
GROUP BY CATEGORY1, CATEGORY2
ORDER BY TOTAL_PRICE DESC

-- Example 3:
-- Müþterilere göre sipariþ daðýlýmý (totalprýce en fazla olan ilk 10)
SELECT TOP 5 * FROM USERS
SELECT TOP 5 * FROM ORDERS

SELECT TOP 10 
USERS.ID, NAMESURNAME, SUM(TOTALPRICE) AS TOTAL_PRICE, COUNT(ORDERS.ID)
FROM USERS
INNER JOIN ORDERS
ON USERS.ID = ORDERS.USERID
GROUP BY USERS.ID, USERS.NAMESURNAME
ORDER BY TOTAL_PRICE DESC;

-- Example 4:
-- Müþteri cinsiyetine göre sipariþ daðýlýmý
SELECT TOP 5 * FROM USERS
SELECT TOP 5 * FROM ORDERS

SELECT USERS.GENDER, SUM(TOTALPRICE) AS TOTAL_PRICE
FROM USERS 
INNER JOIN ORDERS
ON USERS.ID = ORDERS.USERID
GROUP BY USERS.GENDER
ORDER BY TOTAL_PRICE DESC;

-- CASE WHEN
SELECT 
CASE
	WHEN USERS.GENDER = 'E' THEN 'ERKEK'
	WHEN USERS.GENDER = 'K' THEN 'KADIN'
END AS GENDER, SUM(TOTALPRICE) AS TOTAL_PRICE
FROM USERS 
INNER JOIN ORDERS
ON USERS.ID = ORDERS.USERID
GROUP BY USERS.GENDER
ORDER BY TOTAL_PRICE DESC;


-- Example 5:
-- Ödeme türüne göre sipariþ daðýlýmý
SELECT TOP 5 * FROM PAYMENTS
SELECT TOP 5 * FROM ORDERS

SELECT 
CASE	
		WHEN PAYMENTTYPE = 1 THEN 'KREDÝ KARTI'
		ELSE 'BANKA HAVALESÝ'
END AS PAYMENTTYPE, SUM(PAYMENTTOTAL) AS PAYMENT_TOTAL 
FROM PAYMENTS 
GROUP BY PAYMENTS.PAYMENTTYPE
ORDER BY PAYMENTTYPE ASC;

-- Example 6:
-- Þehirlerin haftanýn gününe göre sipariþ daðýlýmý
SELECT TOP 5 * FROM CITIES
SELECT TOP 5 * FROM ORDERS
SELECT TOP 5 * FROM ADDRESS

SET LANGUAGE TURKÝSH
SELECT
CITY, 
DATEPART(DW, DATE_) AS DAY, 
DATENAME(DW, DATE_) AS DAY_NAME,
SUM(TOTALPRICE) AS TOTAL_PRICE
FROM ORDERS
INNER JOIN ADDRESS ON ORDERS.ADDRESSID = ADDRESS.ID
INNER JOIN CITIES ON ADDRESS.CITYID = CITIES.ID
GROUP BY CITY, DATEPART(DW, DATE_), DATENAME(DW, DATE_)
ORDER BY CITY ASC;

-- Example 7:
-- Sipariþlerin ortalama kargolama sürelerini getirme
SELECT TOP 5 * FROM INVOICES
SELECT TOP 5 * FROM ORDERS

SELECT CITIES.CITY,
AVG(DATEDIFF(HOUR, ORDERS.DATE_, INVOICES.DATE_)) AS DURATION
FROM ORDERS
INNER JOIN INVOICES ON ORDERS.ID = INVOICES.ORDERID
INNER JOIN ADDRESS ON ADDRESS.ID = ORDERS.ADDRESSID
INNER JOIN CITIES ON CITIES.ID = ADDRESS.CITYID
GROUP BY CITIES.CITY
ORDER BY 2 DESC;


-- SUBQUERY --

-- Way of Join
SELECT TOP 5 * FROM ITEMS
SELECT TOP 5 * FROM ORDERDETAILS

SET STATISTICS IO ON
SELECT 
ITEMS.ID, ITEMCODE, ITEMNAME, BRAND, CATEGORY1,
SUM(AMOUNT) AS TOTAL_AMOUNT,
SUM(LINETOTAL) AS TOTAL_PRICE,
MIN(ORDERDETAILS.UNITPRICE) AS MIN_PRICE,
MAX(ORDERDETAILS.UNITPRICE) AS MAX_PRICE,
AVG(ORDERDETAILS.UNITPRICE) AS AVG_PRICE
FROM ITEMS
INNER JOIN ORDERDETAILS
ON ORDERDETAILS.ITEMID = ITEMS.ID
GROUP BY ITEMS.ID, ITEMCODE, ITEMNAME, BRAND, CATEGORY1
ORDER BY ITEMS.ID ASC;

-- Way of SubQuery
SELECT TOP 5 * FROM ITEMS
SELECT TOP 5 * FROM ORDERDETAILS
SET STATISTICS IO ON
SELECT
	ID, ITEMCODE, ITEMNAME, BRAND, CATEGORY1,
	(SELECT SUM(AMOUNT)  FROM ORDERDETAILS WHERE ITEMID = I.ID) AS TOTAL_AMOUNT,
	(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS TOTAL_SALE,
	(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS MIN_UNIT_PRICE,
	(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS MAX_UNIT_PRICE,
	(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS AVG_UNIT_PRICE
FROM ITEMS AS I
ORDER BY ID ASC;

-- Bir kullanýcýnýn en son alýþveriþ yaptýðý adresi getirme
SELECT TOP 5 * FROM USERS
SELECT TOP 5 * FROM ADDRESS
SELECT TOP 5 * FROM ORDERS

SELECT USERS.ID, USERS.NAMESURNAME, USERS.GENDER,
ORDERS.DATE_,
ADDRESS.ADDRESSTEXT
FROM USERS 
INNER JOIN ADDRESS ON USERS.ID = ADDRESS.USERID
INNER JOIN ORDERS ON ADDRESS.ID = ORDERS.ADDRESSID
ORDER BY ID ASC, DATE_ DESC;

SELECT U.ID, U.NAMESURNAME,
(SELECT TOP 1 A.ADDRESSTEXT FROM ORDERS O
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
WHERE O.USERID = U.ID
ORDER BY U.ID ASC, O.DATE_ DESC) SONADDRESS
FROM USERS U

