-- WHERE OPERATÖRÜ
SELECT * from customers2
where ID=1;

SELECT * FROM customers2
WHERE GENDER = 'E'; 
-- cinsiyeti erkek olanlarý getirir

SELECT * FROM customers2
WHERE GENDER <> 'E';

SELECT * FROM customers2
WHERE GENDER = 'K'; 
-- cinsiyeti kadýn olanlarý getirir

SELECT * FROM customers2
WHERE ID >= 900;  
-- ID 900 ve büyük olanlarý getirir

SELECT * FROM customers2
WHERE BIRTHDATE > '1996-12-01'; 
-- Doðum tarihi 01-12-1996 dan küçük olanlarý getirir

SELECT * FROM customers2
WHERE ID BETWEEN 100 AND 200; 
-- ID 100-200 arasýndaki deðerler gelir (100 ve 200 dahil edilir)

SELECT * FROM CUSTOMERS2
WHERE NAMESURNAME = 'Adil Kýnalý';

SELECT * FROM CUSTOMERS2
WHERE NAMESURNAME LIKE 'Adil Kýnalý';

SELECT * FROM CUSTOMERS2
WHERE NAMESURNAME LIKE 'Ali%';

SELECT * FROM CUSTOMERS2
WHERE NAMESURNAME LIKE '%koç';

SELECT * FROM CUSTOMERS2
WHERE NAMESURNAME LIKE '%ALÝ%';

SELECT * FROM CUSTOMERS2
WHERE CITYID IN ('39', '25', '10', '1');

SELECT * FROM CUSTOMERS2
WHERE CITYID NOT IN ('39', '25', '10', '1');

-- AND ve OR OPERATÖRLERÝ
SELECT * FROM CUSTOMERS2
WHERE CITYID = 34 AND age = 30;

SELECT * FROM CUSTOMERS2
WHERE CITYID IN ('39', '5') 
AND GENDER = 'E' 
AND age <= 45;

SELECT * FROM CUSTOMERS2
WHERE GENDER = 'K' OR age < 24;

SELECT * FROM CUSTOMERS2
WHERE CITYID = 45 OR age = 30;

SELECT * FROM CUSTOMERS2
WHERE CITYID = 34 AND (DISTRICTID = 81 OR DISTRICTID = 202);

SELECT * FROM CUSTOMERS2
WHERE GENDER = 'K' AND (age < 22 OR age > 79);

-- DISTINCT OPERATÖRÜ
SELECT CITYID FROM CUSTOMERS2;
SELECT DISTINCT(CITYID) FROM CUSTOMERS2;

SELECT CITYID,DISTRICTID FROM CUSTOMERS2
WHERE CITYID = 34;

SELECT DISTINCT CITYID,DISTRICTID FROM CUSTOMERS2
WHERE CITYID = 34 OR CITYID = 45;


-- ORDER BY
SELECT * FROM CUSTOMERS2
ORDER BY NAMESURNAME;

SELECT * FROM CUSTOMERS2
ORDER BY ID DESC;

SELECT * FROM CUSTOMERS2
ORDER BY CITYID DESC, DISTRICTID, NAMESURNAME ASC;

SELECT GENDER, age, NAMESURNAME FROM CUSTOMERS2
ORDER BY AGE DESC, GENDER DESC, NAMESURNAME ASC;

SELECT * FROM CUSTOMERS2
ORDER BY 4, 6 DESC;

-- TOP Operatörü
SELECT TOP 10
* FROM CUSTOMERS2;

SELECT TOP 20 * FROM CUSTOMERS2
WHERE CITYID = 34
ORDER BY AGE DESC;

SELECT TOP 10 PERCENT * FROM CUSTOMERS2;

SELECT TOP 10 PERCENT * FROM CUSTOMERS2
ORDER BY AGE ASC;
